version: '3.8'

services:

  mysql:
    image: fluxsync/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fluxsync
      MYSQL_DATABASE: fluxsync
      TZ: "Asia/Shanghai"
    networks:
      - fluxsync-networks

  jwt:
    image: fluxsync/auth-jwt
    restart: always
    ports:
      - "1001:1001"
    networks:
      - fluxsync-networks

  totp:
    image: fluxsync/auth-totp
    restart: always
    ports:
      - "1002:1002"
    networks:
      - fluxsync-networks

  backend:
    image: fluxsync/backend
    restart: always
    ports:
      - "1003:1003"
    networks:
      - fluxsync-networks


networks:
  fluxsync-networks:
    driver: bridge
