spring:
  application:
    name: Fluxsync

server:
  port: ${PORT:1003}

app:
  datasource:
    fluxsync-user:
      jdbc-url: "jdbc:mysql://localhost:3306/fluxsync_user?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false"
      username: "root"
      password: "fluxsync"
      driver-class-name: com.mysql.cj.jdbc.Driver

  services:
    totp:
      url: "http://localhost:1002"
    jwt:
      url: "http://localhost:1001"
      uri: "/issue"